name: CI

on: [push, pull_request]

jobs:
  test:
    name: 'Go Test ${{ matrix.GO_VERSION }}'
    strategy:
      matrix:
        GO_VERSION: ['1.15', '1.16', '1.17']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^${{ matrix.GO_VERSION }}
      - run: go get ./...
      - run: go test ./...